apiVersion: extensions/v1beta
kind: Ingress
metadata:
    name: "azkub01-1857"
    labels:
        app: "azkub01-1857"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: git-kub-clus01-azkub01-1857.2cda881d00c045118573.centralus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "azkub01-1857"
                servicePort: 8080
